# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "dist"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./dist/my-tool ./cmd/cli/"
# Binary file yields from `cmd`.
bin = "dist/my-tool"
# Customize binary.
full_bin = "STRIPE_SECRET=sk_test_51MBtiKJNMtnorzh4acgs8lTqeaKWbXikx3zJbBMDGEFOjJVgEJxA9uRxlYKANRPikR2NkW9EpqWrxbnoPoEaFOw400zkrUo9ld STRIPE_KEY=pk_test_51MBtiKJNMtnorzh4794j7mHcLEtGoa3NOb66Q83OQ4siizFndK0LKJDg9vmtcA1LZPhdzXGiV0YtzTje4ylJG4s500vRf0UMX9 ./dist/my-tool"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "gohtml"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "dist", "vendor", "frontend/node_modules"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = []
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true